// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf21mfTydPhKnPhS_E2Q6672m0YdeQTik',
    appId: '1:718274219517:web:2a61e54c5e7ae4bee31d94',
    messagingSenderId: '718274219517',
    projectId: 'metri-valet-d7486',
    authDomain: 'metri-valet-d7486.firebaseapp.com',
    storageBucket: 'metri-valet-d7486.firebasestorage.app',
    measurementId: 'G-HH6B813RZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUAvk1buE759JsihuxOCrkbxRJOm8Pio',
    appId: '1:718274219517:android:6b8519135105830ee31d94',
    messagingSenderId: '718274219517',
    projectId: 'metri-valet-d7486',
    storageBucket: 'metri-valet-d7486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6bCoif0uyOL0fZQA92MfLyN_2ej5yk8',
    appId: '1:718274219517:ios:5206257b0a383117e31d94',
    messagingSenderId: '718274219517',
    projectId: 'metri-valet-d7486',
    storageBucket: 'metri-valet-d7486.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );
}
